# Generated by Django 3.0.5 on 2020-04-15 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='name',
            old_name='name',
            new_name='nickname',
        ),
    ]
